name: Documenting and Testing
title: RegTest
subtitle:  Detailed Templates for Regulated Applications
url:
description: Website with templates for documenting and testing FDA and EU regulated life science applications. Templates are based on GAMP5, and ISO security standards, most can be output in several formats (doc, pdf, html, markdown), with enough detail for easy customization.
baseurl: /regtest
url:
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
